### ISSUE TITLE
fyi https://github.com/tonygoold/ObjClang

### ISSUE THREAD

**Issue by johndpope** [daniel-beard/libclangObjCExperiments#1]
I am impressed with your project and efforts. 
I couldn't get the sample Source.m (not included) to decompile though. 
Found this alternative repo in the process of trying to fix problem.

**Comment by daniel-beard** [comment]
Thanks! I was aware of that repository when I started, but wanted to explore licClang a little from scratch. I've since moved on to using libTooling directly http://clang.llvm.org/docs/LibTooling.html which better fits my needs.

**Comment by johndpope** [comment]
objective-c seems so long ago with swift these days. 
I'm closing out older github tickets. Thanks for your efforts @daniel-beard
